// Regenerate src/cribTable.ts: `npx tsx packages/engine/scripts/gen-crib-table.ts`
//
// Estimates the average crib score for every pair of thrown ranks, assuming the other two crib
// cards and the cut are random among the remaining cards. Real opponents throw a little smarter,
// but this is the standard approximation and plenty good for ranking discards.
import { writeFileSync } from "node:fs";
import { type Card, SUITS, createDeck, sameCard, scoreHand, seededRandom } from "../src/index.js";

const SAMPLES = 20_000;
const random = seededRandom(121);
const deck = createDeck();
const table: number[][] = Array.from({ length: 14 }, () => new Array<number>(14).fill(0));

for (let a = 1; a <= 13; a++) {
  for (let b = a; b <= 13; b++) {
    // Off-suit throw (suits rarely matter for a crib, which needs all five to flush).
    const thrown: Card[] = [
      { rank: a as Card["rank"], suit: SUITS[0] },
      { rank: b as Card["rank"], suit: SUITS[1] },
    ];
    const rest = deck.filter((c) => !thrown.some((t) => sameCard(t, c)));
    let total = 0;
    for (let i = 0; i < SAMPLES; i++) {
      // Partial Fisher–Yates: pick 3 distinct cards (2 more for the crib, 1 cut).
      const pool = rest.slice();
      for (let k = 0; k < 3; k++) {
        const j = k + Math.floor(random() * (pool.length - k));
        [pool[k], pool[j]] = [pool[j]!, pool[k]!];
      }
      total += scoreHand([...thrown, pool[0]!, pool[1]!], pool[2]!, true).total;
    }
    table[a]![b] = table[b]![a] = Math.round((total / SAMPLES) * 100) / 100;
  }
}

const rows = table.map((row) => `  [${row.join(", ")}],`).join("\n");
writeFileSync(
  new URL("../src/cribTable.ts", import.meta.url),
  `// Generated by scripts/gen-crib-table.ts — do not edit by hand.
/** CRIB_EV[a][b]: average crib points when ranks a and b are thrown (index 0 unused). */
export const CRIB_EV: readonly (readonly number[])[] = [
${rows}
];
`,
);
console.log("5-5:", table[5]![5], " K-A:", table[13]![1], " 7-8:", table[7]![8]);
